VFS Modal Bugfixing
scireum/sirius-biz pull request #1022
Opened 2021-03-11 09:56 UTC by qw3ry

ymo found some bugs:
- pagination was only 5 items
- search does work with enter key, but not with the button
- when clicking on breadcrumbs, a js error occurred

Furthermore, the search field was not reset when changing directory, which doesn't make much sense

2021-03-11 10:02 UTC, sabieber requested changes

2021-03-11 10:02 UTC, sabieber commented on src/main/resources/default/extensions/wondergem-page/storage-vfs-modals.html.pasta
> +                    createRow: function (child, _modal, resolve, cd) {
could we choose a more descriptive name?

2021-03-11 10:03 UTC, sabieber commented on src/main/resources/default/extensions/wondergem-page/storage-vfs-modals.html.pasta
> +                    createRow: function (child, _modal, resolve, cd) {
roughly 5 mins after merging this we have forgot what cd stands for ;)

2021-03-11 10:58 UTC, idlira approved these changes

2021-03-11 14:24 UTC, ymo-sci approved these changes

2021-03-12 06:05 UTC, mkeckmkeck approved these changes

2021-03-12 13:35 UTC, jmuscireum approved these changes

2021-03-12 13:36 UTC, sabieber approved these changes

2021-03-12 13:36 UTC, andyHa approved these changes

2021-03-12 13:36 UTC, merged