Provides LookupTables a abstraction over CodeLists and Jupiter IDBTables.
scireum/sirius-biz pull request #1032
Opened 2021-03-19 18:35 UTC by andyHa

2021-03-22 07:13 UTC, jmuscireum requested changes

2021-03-22 07:13 UTC, jmuscireum commented on src/main/java/sirius/biz/codelists/LookupTable.java
> + * Next to the code these is always a name field which is used to provide a textual representation of the field. This
```suggestion
 * Next to the code there is always a name field which is used to provide a textual representation of the field. This
```

2021-03-22 07:13 UTC, jmuscireum commented on src/main/java/sirius/biz/codelists/LookupTable.java
> + * A actually control how a lookup table is represented internally, a config section within <tt>lookup-tables</tt>
```suggestion
 * To actually control how a lookup table is represented internally, a config section within <tt>lookup-tables</tt>
```
?

2021-03-22 07:13 UTC, jmuscireum commented on src/main/java/sirius/biz/codelists/LookupTable.java
> +     * Sugesst several entries for the given search term using the currently active language.
```suggestion
     * Suggests several entries for the given search term using the currently active language.
```

2021-03-22 07:13 UTC, jmuscireum commented on src/main/java/sirius/biz/codelists/LookupTable.java
> +     * Sugesst several entries for the given search term using the given language.
```suggestion
     * Suggests several entries for the given search term using the given language.
```

2021-03-22 07:13 UTC, jmuscireum commented on src/main/java/sirius/biz/codelists/LookupTables.java
> + * This is mainly reqired to instantiate the concrete type of lookup table for a given table name. Depending on
```suggestion
 * This is mainly required to instantiate the concrete type of lookup table for a given table name. Depending on
```

2021-03-22 07:13 UTC, jmuscireum commented on src/main/java/sirius/biz/codelists/LookupTables.java
> + * the configuration, this could either by a {@link CodeLists code list} or a table backed by
```suggestion
 * the configuration, this could either be a {@link CodeLists code list} or a table backed by
```

2021-03-22 07:13 UTC, jmuscireum commented on src/main/resources/component-biz.conf
> +# tables and use this data. Further more such Jupiter tables can be combined, so that a default table (e.g. defined
```suggestion
# tables and use this data. Furthermore such Jupiter tables can be combined, so that a default table (e.g. defined
```

2021-03-22 08:03 UTC, sabieber requested changes

2021-03-22 08:13 UTC, idlira requested changes
Some test cases around the framework would be the 👑 😇

2021-03-22 08:13 UTC, idlira commented on src/main/java/sirius/biz/codelists/LookupTable.java
> + * A lookup table has a normalied code field, which is used e.g. in a database entity to represent a value. Using
```suggestion
 * A lookup table has a normalized code field, which is used e.g. in a database entity to represent a value. Using
```

2021-03-22 08:15 UTC, andyHa commented on src/main/java/sirius/biz/codelists/CustomLookupTable.java
> +class CustomLookupTable extends LookupTable {
Custom properties - there will be a set of standard ones for sellsite and then customers can provide their own for enterprise installations

2021-03-22 08:17 UTC, andyHa commented on src/main/java/sirius/biz/codelists/LookupTables.java
> +                    new IDBLookupTable(extension, jupiter.getDefault().idb().table(customTable));
Nope - at least not until there is a usecase for it..

2021-03-22 08:18 UTC, andyHa commented on src/main/java/sirius/biz/codelists/CustomLookupTable.java
> +    }
This is actually a "backport" of Optional.or which will be accessible once we're able to update to a more current Java version...

2021-03-22 08:19 UTC, andyHa commented on src/main/java/sirius/biz/codelists/LookupTable.java
> +            codesAreLowercase = false;
The external API uses constants in the config - this is entirely internal

2021-03-22 08:20 UTC, andyHa commented on src/main/java/sirius/biz/codelists/LookupTableEntry.java
> +                                                 Formatter.create("${code}[ (${name})]")
This will most probably be fine tuned later - Most probably we sometimes want to be able to suppress the code anyway.

2021-03-22 10:00 UTC, jmuscireum approved these changes

2021-03-22 11:00 UTC, sabieber commented on src/main/java/sirius/biz/codelists/LookupTable.java
> +            codesAreLowercase = false;
Yes and I think the code would be cleaner with the enum (private) but its not that important :)

2021-03-23 08:44 UTC, andyHa commented on src/main/java/sirius/biz/codelists/CodeLists.java
> +        return getCurrentTenant(codeListName).orElseThrow(this::warnAboutMissingTenant);
Nope, code-lists can have a special way to determine a tenant based on the current space - e.g. a sellsite shop - this isn't new functionality however, just made public accessible...

2021-03-23 08:50 UTC, idlira approved these changes

2021-03-23 09:21 UTC, sabieber approved these changes

2021-03-23 09:23 UTC, mkeckmkeck approved these changes

2021-03-23 09:23 UTC, mkeckmkeck commented on src/main/java/sirius/biz/codelists/README.md
> +which provide access to more or less static date like "list of all known countries" etc.
```suggestion
which provide access to more or less static data like "list of all known countries" etc.
```

2021-03-23 09:23 UTC, mkeckmkeck commented on src/main/resources/component-biz.conf
> +        # Determines if the table supports scanning. Scannin in this case means listing all possible codes (most
```suggestion
        # Determines if the table supports scanning. Scanning in this case means listing all possible codes (most
```

2021-03-23 10:52 UTC, merged