Fixes error messages for import jobs.
scireum/sirius-biz pull request #1074
Opened 2021-05-04 13:31 UTC by andyHa

2021-05-04 13:33 UTC, meg1502 approved these changes

2021-05-04 13:35 UTC, idlira requested changes

2021-05-04 13:35 UTC, idlira commented on src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java
> +    private static final String NLS_KEY_ERROR_IN_ROW_AND_FILE = "LineBasedJob.errorInRowAndFile";
LineBasedJob.errorInFileAndRow ?

2021-05-04 13:35 UTC, idlira commented on src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java
> +                                     .withNLSKey("LineBasedJob.failureInRowAndFile")
failureInFileAndRow

2021-05-04 13:45 UTC, idlira approved these changes

2021-05-04 13:49 UTC, meg1502 approved these changes

2021-05-04 14:42 UTC, mkeckmkeck approved these changes

2021-05-04 15:55 UTC, cschierle approved these changes

2021-05-05 06:03 UTC, jmuscireum approved these changes

2021-05-05 06:04 UTC, merged