Logs empty conversion results as errors in a tenant specific standby process
scireum/sirius-biz pull request #1104
Opened 2021-06-08 12:30 UTC by meg1502

only in case of an error we query the processes framework, as we want to be as quick as possible for successful conversions

Fixes: OX-6843

2021-06-08 12:38 UTC, sabieber approved these changes

2021-06-08 12:41 UTC, andyHa requested changes

2021-06-08 12:41 UTC, andyHa commented on src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
> +                 try {
extract method?

2021-06-08 12:41 UTC, andyHa commented on src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
> +                                 conversionProcess.getBlobToConvert().getBlobKey()));
extract method?

2021-06-08 12:42 UTC, andyHa commented on src/main/resources/biz_de.properties
> +ConversionEngine.processTitle = Bildkonvertierung
Könnte auch ein Video etc. sein - vllt "Datei-Konvertierung" oder sowas(?)

2021-06-08 12:43 UTC, sabieber commented on src/main/resources/biz_de.properties
> +ConversionEngine.processTitle = Bildkonvertierung
Oder evtl "Medienkonvertierung"?

2021-06-08 14:42 UTC, andyHa requested changes

2021-06-08 14:42 UTC, andyHa commented on src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
> +        processes.executeInStandbyProcessForCurrentTenant("conversion",
is the tenant always properly set (e.g. when BlobDispatcher is in action)? oder do we have to supply it manually

2021-06-08 14:42 UTC, andyHa commented on src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
> +                                                          processContext -> processContext.log(ProcessLog.error()
extract again - this break horribly

2021-06-08 16:34 UTC, andyHa approved these changes

2021-06-08 16:35 UTC, sabieber approved these changes

2021-06-09 07:28 UTC, idlira approved these changes

2021-06-09 08:00 UTC, qw3ry approved these changes

2021-06-09 08:06 UTC, mkeckmkeck approved these changes

2021-06-09 08:06 UTC, merged