Adds public methods to retrieve display strings for LookupValue
scireum/sirius-biz pull request #1114
Opened 2021-06-15 14:42 UTC by meg1502

Fixes: OX-6824

2021-06-15 14:44 UTC, andyHa commented on src/main/java/sirius/biz/codelists/LookupValues.java
> +    public Map<String, String> resolveDisplayStrings() {
shouldn't  we return a List<Tuple<String, String>> here?

2021-06-15 14:46 UTC, andyHa requested changes

2021-06-15 14:46 UTC, andyHa commented on src/main/java/sirius/biz/codelists/LookupValues.java
> +        return codeAndDisplays;
`return data().stream().map(code -> Tuple.create(code, isplay.resolveDisplayString(getTable(), code)).collect(Collectors.toList());` or the like

2021-06-15 14:54 UTC, sabieber approved these changes

2021-06-15 14:54 UTC, sabieber commented on src/main/java/sirius/biz/codelists/LookupValue.java
> +    }
Optional: Unter die Methode schieben die mehr macht als nur n getter zu sein

2021-06-16 11:43 UTC, cschierle approved these changes

2021-06-17 07:23 UTC, sabieber approved these changes

2021-06-17 07:24 UTC, qw3ry approved these changes

2021-06-17 07:57 UTC, ymo-sci approved these changes

2021-06-17 08:09 UTC, mkeckmkeck approved these changes

2021-06-18 07:03 UTC, merged