Adds the current file and row in the ErrorContext
scireum/sirius-biz pull request #1148
Opened 2021-07-13 09:57 UTC by idlira

The DictionaryBasedArchiveImportJob parses multiple files (eg. CSV) from an archive, so we identify the current file and row being processed

Fixes: OX-7060

2021-07-13 10:23 UTC, ymo-sci approved these changes

2021-07-13 10:23 UTC, andyHa requested changes

2021-07-13 10:23 UTC, andyHa commented on src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
> +                return true;
```suggestion
                errorContext.removeContext(ERROR_CONTEXT_ROW);
                return true;
```

2021-07-13 11:35 UTC, sabieber approved these changes

2021-07-13 14:41 UTC, andyHa approved these changes

2021-07-13 15:30 UTC, sabieber approved these changes

2021-07-14 05:08 UTC, mkeckmkeck approved these changes

2021-07-14 06:27 UTC, merged