extend wondergem footer for support-links, always redirect to given link
scireum/sirius-biz pull request #1169
Opened 2021-07-21 09:41 UTC by ymo-sci

- depends on https://github.com/scireum/sirius-web/pull/893
- fixes: SIRI-396

2021-07-21 10:07 UTC, andyHa requested changes

2021-07-21 10:07 UTC, andyHa commented on src/main/java/sirius/biz/tenants/TenantController.java
> -            webContext.respondWith().redirectTemporarily("/tenants/select");
I'd keep the original url if "main" is present, as this is commonly used to "go back to the main tenant and select a new one"

2021-07-21 10:46 UTC, sabieber approved these changes

2021-07-21 10:46 UTC, sabieber commented on src/main/resources/default/extensions/wondergem-page-menu/footer.html.pasta
> +                            const fakeElem = document.createElement('textarea');
Optional: fakeElem -> _fakeElem

2021-07-26 07:18 UTC, sabieber approved these changes

2021-07-26 08:04 UTC, meg1502 approved these changes

2021-07-26 08:09 UTC, qw3ry approved these changes

2021-07-26 08:12 UTC, fhaScireum approved these changes

2021-07-26 08:13 UTC, andyHa approved these changes

2021-07-26 09:53 UTC, cschierle approved these changes

2021-07-28 06:08 UTC, merged