Enhances the ErrorContext
scireum/sirius-biz pull request #1220
Opened 2021-09-06 14:01 UTC by idlira

- moves a method into sirius-db (see https://github.com/scireum/sirius-db/pull/448)
- adds methods to execute a task/producer and apply a failure description before the re-throwing

Fixes: OX-7244

2021-09-06 14:04 UTC, sabieber approved these changes

2021-09-06 14:18 UTC, cschierle approved these changes

2021-09-07 05:15 UTC, mkeckmkeck approved these changes

2021-09-07 13:14 UTC, andyHa requested changes

2021-09-07 13:34 UTC, meg1502 commented on src/main/java/sirius/biz/process/ErrorContext.java
>                              .handle();
Isn't this unnecessary as Exceptions.handle won't log HandledExceptions anyway?

2021-09-07 14:05 UTC, merged