Allows to mark a process output as system output
scireum/sirius-biz pull request #1287
Opened 2021-11-02 11:52 UTC by cschierle

which is only visible to admins

Fixes: OX-7702

2021-11-02 12:06 UTC, sabieber approved these changes

2021-11-02 12:08 UTC, idlira approved these changes

2021-11-02 13:36 UTC, andyHa requested changes

2021-11-02 13:36 UTC, andyHa commented on src/main/resources/default/templates/biz/process/process.html.pasta
> +                        <i:if test="@!output.isSystemOutput() || user().hasPermission('permission-manage-all-processes')">
shouldn't we also enforce this check when actually rendering the output (like in the controller)?

2021-11-02 14:49 UTC, andyHa approved these changes

2021-11-03 09:38 UTC, sabieber approved these changes

2021-11-03 14:57 UTC, ymo-sci approved these changes

2021-11-03 15:14 UTC, merged