move annotation to make pre-authorized articles accessible (and not all without an authKey)
scireum/sirius-biz pull request #1290
Opened 2021-11-04 20:30 UTC by ymo-sci

2021-11-04 20:36 UTC, andyHa requested changes

2021-11-04 20:36 UTC, andyHa commented on src/main/java/sirius/biz/tycho/kb/KnowledgeBaseController.java
> +    @LoginRequired
This is handled in "resolve" and should not be enforced here, as there might as well be "public" articles.

2021-11-08 06:24 UTC, mkeckmkeck approved these changes

2021-11-08 09:19 UTC, qw3ry approved these changes

2021-11-09 09:44 UTC, sabieber approved these changes

2021-11-09 10:17 UTC, merged