ports system/schema to tycho
scireum/sirius-biz pull request #1299
Opened 2021-11-11 15:11 UTC by ymo-sci

<img width="1394" alt="Bildschirmfoto 2021-11-11 um 15 38 05" src="https://user-images.githubusercontent.com/55080004/141321482-f134d8e1-53f4-4791-838d-17049a1aa364.png">
<img width="1407" alt="Bildschirmfoto 2021-11-11 um 15 37 58" src="https://user-images.githubusercontent.com/55080004/141321494-2fd8c830-6d0c-4444-be7e-69aba0ada402.png">
<img width="1412" alt="Bildschirmfoto 2021-11-11 um 15 37 38" src="https://user-images.githubusercontent.com/55080004/141321496-cd605c0f-671b-40d8-8f45-e250c2c15c83.png">

2021-12-14 13:14 UTC, sabieber commented on src/main/resources/default/templates/biz/model/schema.html.pasta
> +            let $row = $(this).parent().parent();
Don't want we to switch to vanilla JS where possible in tycho?

2021-12-14 14:14 UTC, andyHa requested changes

2021-12-14 14:14 UTC, andyHa commented on src/main/resources/default/assets/styles/biz-misc.scss
> +
nope, we use declarative styles / classes now...

2021-12-14 14:14 UTC, andyHa commented on src/main/resources/default/assets/styles/biz-misc.scss
> +
also, these seem to be default values(?)

2021-12-14 14:14 UTC, andyHa commented on src/main/resources/default/templates/biz/model/schema.html.pasta
> +                    <table id="schemaTable" class="table table-sm table-striped">
in Tycho we commonly only use class="table"

2021-12-14 14:14 UTC, andyHa commented on src/main/resources/default/templates/biz/model/schema.html.pasta
> +                        $('#schemaList').html('<tr><td colspan="3" class="align-center">'
I'd kille the whole table and replicate the look&feel of t:emptyCheck here....

2022-01-13 15:37 UTC, sabieber approved these changes

2022-01-13 16:27 UTC, merged