Does not delete source directory when transferring content.
scireum/sirius-biz pull request #1360
Opened 2022-02-15 14:13 UTC by fhaScireum

This is done as the source directory should probably not (or even can't) be deleted and deleting the source directory at the source location can be accomplished via TransferMode#MOVE.

- Fixes: SE-11421

2022-02-15 14:45 UTC, mkeckmkeck approved these changes

2022-02-15 21:03 UTC, andyHa approved these changes

2022-02-16 09:02 UTC, ymo-sci approved these changes

2022-02-16 10:40 UTC, sabieber requested changes

2022-02-16 10:40 UTC, sabieber commented on src/main/java/sirius/biz/storage/layer3/Transfer.java
> +                transferDirectory(child, destinationDirectory.findChild(child.name()), deleteContent, deleteContent);
Even if thats correct this looks like an error, so maybe explain why the same param is passed twice here :)

2022-02-16 10:40 UTC, sabieber commented on src/main/java/sirius/biz/storage/layer3/Transfer.java
> +            transferDirectory(source, destination.findChild(source.name()), delete, delete);
Even if thats correct this looks like an error, so maybe explain why the same param is passed twice here :)

2022-02-16 11:52 UTC, sabieber approved these changes

2022-02-16 11:59 UTC, merged