Adds a AllInListCheck for FieldDefinition
scireum/sirius-biz pull request #1368
Opened 2022-02-22 12:42 UTC by idlira

This checks splits the field's value using the provided separator and parses all single items against the provided list.

**Example**
List: `[foo, bar]`; Separator: `,`

- `foo` -> OK
- `foo,bar` -> OK
- `foo, bar` -> OK
- `foo, bar`-> _Invalid value ' bar'_ when using `#checkUntrimmed`
- `foo,yyy,zzz` -> _Invalid values 'yyy', 'zzz'_

Fixes: OX-8115

2022-02-22 12:45 UTC, sabieber requested changes

2022-02-22 12:45 UTC, sabieber commented on src/main/java/sirius/biz/importer/format/AllInListCheck.java
> +    public AllInListCheck(Collection<String> validValues, String separator) {
Think it would favour code formatting when the parameters would be switched

2022-02-22 12:45 UTC, sabieber commented on src/main/java/sirius/biz/importer/format/AllInListCheck.java
> +                                                                          ", "))
Collectors joining?

2022-02-22 12:48 UTC, andyHa requested changes

2022-02-22 12:48 UTC, andyHa commented on src/main/java/sirius/biz/importer/format/AllInListCheck.java
> +        }
Stream-pipeline?

2022-02-22 12:48 UTC, andyHa commented on src/main/java/sirius/biz/importer/format/AllInListCheck.java
> +                                                                                      .collect(Collectors.toList()),
Collectors.joining(", ")

2022-02-22 12:48 UTC, andyHa commented on src/main/java/sirius/biz/importer/format/AllInListCheck.java
> +        }
Stream s = Arrays.stream(split);
if (trim) {
 s = s.map(String::trim);
 }
 List<String> invalidItems = s.filter(!contains).toList();

2022-02-22 12:59 UTC, sabieber approved these changes

2022-02-22 13:15 UTC, andyHa requested changes

2022-02-22 13:15 UTC, andyHa commented on src/main/java/sirius/biz/importer/format/AllInListCheck.java
> +            items.map(String::trim);
items =
```suggestion
            items = items.map(String::trim);
```

2022-02-22 14:59 UTC, cschierle approved these changes

2022-02-23 07:35 UTC, ymo-sci approved these changes

2022-02-23 09:09 UTC, merged