Ensures that processes marked as admin-only are always executed in an admin tenant
scireum/sirius-biz pull request #1378
Opened 2022-03-11 13:42 UTC by cschierle

- Exposes and uses some existing logic in `TenantController` to check, if a user is currently spying another tenant.
- Adds the admin-only marker as a method in BasicJobFactory, so it can be overridden in subclasses.

Other projects using this might define different rulesets for when a process is considered as admin-only. So I thought performing the check via a method provides enough flexibility while still having a suitable default behavior.

Feel free to discuss possible other solutions. Comments are very much welcome :)

2022-03-11 13:57 UTC, cschierle commented
Maybe the naming could be improved.

The process would still be executed in the context of the tenant the user is currently spying. Only the process entity is assigned to the admin tenant, so it is not visible to the other tenant.

2022-03-15 12:54 UTC, andyHa commented
This approach violates the decoupling of the individual frameworks. The idea is, that jobs, processes and user management make little to no assumptions of implementation of others. Therefore this needs to be split up:

Therefore the processes framework should remain untouched. Also, we don't need to modify interactive jobs, as they don't leave any traces. Therefore, we can poll most of the logik (see inline comments) into **BatchProcessJobFactory**.

Now the hard part is to untangle the user management. For this, we need to introduce a new class "SpyUser" which contains a single field "UserInfo rootUser". This needs to be attached to the UserInfo in TenantUserManager#becomeSpyUser and TenantUserManager#createUserWithTenant. In BatchProcessJobFactory#startWithContext we can then check for "shouldExecuteAsSystemTenant" and also user.tryAs(SpyUser.class). If this is filled, we can create the process as root user.

2022-03-15 12:56 UTC, andyHa requested changes

2022-03-15 12:56 UTC, andyHa commented on src/main/java/sirius/biz/jobs/BasicJobFactory.java
> +    protected boolean shouldExecuteInAdminTenant() {
move to BatchProcessJobFactory

2022-03-15 12:56 UTC, andyHa commented on src/main/java/sirius/biz/jobs/BasicJobFactory.java
> +            if (TenantController.isCurrentlySpying(request) && shouldExecuteInAdminTenant()) {
interative jobs don't matter as they don't create processes for other tenants...

2022-03-15 12:56 UTC, andyHa commented on src/main/java/sirius/biz/process/Processes.java
> -        process.setTenantId(user.getTenantId());
handle in BatchProcessJobFactory

2022-03-15 12:56 UTC, andyHa commented on src/main/java/sirius/biz/tenants/TenantController.java
> -    private boolean isCurrentlySpying(WebContext webContext) {
encapsulate in SpyUser as attachment to the UserInfo...

2022-03-18 11:47 UTC, sabieber approved these changes

2022-03-18 13:45 UTC, andyHa reviewed
Minor improvements as comments...

2022-03-18 13:45 UTC, andyHa commented on src/main/java/sirius/biz/jobs/batch/BatchProcessJobFactory.java
> +                              .orElse(UserContext.getCurrentUser());
```suggestion
                              .orElseGet(UserContext::getCurrentUser);
```

2022-03-18 13:45 UTC, andyHa commented on src/main/java/sirius/biz/web/SpyUser.java
> +public class SpyUser extends Composable {
```suggestion
public class SpyUser {
```

2022-03-18 15:59 UTC, sabieber approved these changes

2022-03-21 13:49 UTC, merged