Added parameter to set allowCustomEntries in lookupValue from template
scireum/sirius-biz pull request #1379
Opened 2022-03-15 09:20 UTC by ReadMails-ReallyFast

Fixes: OX-8246

2022-03-15 09:27 UTC, cschierle approved these changes

2022-03-15 09:36 UTC, andyHa requested changes

2022-03-15 09:36 UTC, andyHa commented on src/main/resources/default/taglib/t/lookupValue.html.pasta
> +                allowCustomEntries="@allowCustomEntries && value.acceptsCustomValues()" class="@class"
For boolean expressions, tagliatelle knows that an expression is present, thus no @ is needed
```suggestion
                allowCustomEntries="allowCustomEntries && value.acceptsCustomValues()" class="@class"
```

2022-03-15 09:36 UTC, andyHa commented on src/main/resources/default/taglib/t/lookupValue.html.pasta
> +                allowCustomEntries="@allowCustomEntries && value.acceptsCustomValues()" class="@class"
Also, shouldn't  this overwrite the value.acceptsCustomValues()? (rather than just suppressing it?)

2022-03-15 09:36 UTC, andyHa commented on src/main/resources/default/taglib/w/lookupValue.html.pasta
> +            allowCustomEntries: @allowCustomEntries && @value.acceptsCustomValues(),
s.a.

2022-03-15 12:46 UTC, sabieber approved these changes

2022-03-15 12:46 UTC, sabieber commented on src/main/resources/default/taglib/t/lookupValue.html.pasta
> +<i:arg name="allowCustomEntries" type="boolean" default="true"/>
```suggestion
<i:arg name="allowCustomEntries" type="boolean" default="@value.acceptsCustomValues()"/>
```

2022-03-15 12:46 UTC, sabieber commented on src/main/resources/default/taglib/t/lookupValue.html.pasta
> +                allowCustomEntries="@allowCustomEntries && value.acceptsCustomValues()" class="@class"
```suggestion
                allowCustomEntries="@allowCustomEntries" class="@class"
```

2022-03-15 13:33 UTC, idlira approved these changes

2022-03-16 08:05 UTC, andyHa approved these changes

2022-03-16 08:07 UTC, merged