Fixes a StringIndexOutOfBoundsException exception
scireum/sirius-biz pull request #1392
Opened 2022-04-14 14:13 UTC by idlira

Calling http://.../dasd/ leads to an expected 404 (Page not found), but http://.../dasd (without trailing slash) causes a StringIndexOutOfBoundsException exception

Fixes: SIRI-541

2022-04-14 15:10 UTC, meg1502 approved these changes
Maybe we could even change the constant, as every time its used '/ is appended anyway.


if we do this, we could also change `URI_PREFIX_LENGTH` from a own constant to a simple call to `URI_PREFIX`.length()

2022-04-14 15:56 UTC, andyHa commented
Please update the constant so that we don't always construct a new StringBuilder+String on each invocation.
Also please keep the constant length around, which also saves an evaluation each time (afaik, javac doesn't perform a constant propagation in this case...)...

2022-04-14 15:57 UTC, andyHa requested changes

2022-04-19 06:56 UTC, meg1502 approved these changes

2022-04-19 06:59 UTC, sabieber approved these changes

2022-04-19 08:21 UTC, meg1502 approved these changes

2022-04-19 08:43 UTC, sabieber approved these changes

2022-04-19 10:25 UTC, mkeckmkeck approved these changes

2022-04-19 10:43 UTC, merged