Creates a helper to show grouped actions and uses this for /jobs
scireum/sirius-biz pull request #1453
Opened 2022-08-25 11:42 UTC by andyHa

![grafik](https://user-images.githubusercontent.com/875799/186655342-f04ce53c-e2bb-4ef6-9f8c-3d0a97513722.png)

2022-08-25 12:06 UTC, cschierle approved these changes

2022-08-25 12:07 UTC, sabieber requested changes

2022-08-25 12:07 UTC, sabieber commented on src/main/resources/default/taglib/t/actions.html.pasta
> +            } else if (event.keyCode === 27) {
Instead of keyCode 27 (which is a hard to remember magic number) compare `event.key` to `"Escape"`

2022-08-25 12:23 UTC, cschierle commented on src/main/resources/default/taglib/t/actions.html.pasta
> +            if (event.keyCode === 13 && document.querySelectorAll('.action-visible-js').length === 1) {
It's in the comment below, but you are right, this would make the keys even clearer 👍

2022-08-25 12:30 UTC, sabieber commented on src/main/resources/default/taglib/t/actions.html.pasta
> +            if (event.keyCode === 13 && document.querySelectorAll('.action-visible-js').length === 1) {
Yes but `KeyboardEvent.keyCode` is obsolete anyways:
> Unerwünscht: Dieses Feature wurde aus den Webstandards entfernt

2022-08-25 13:20 UTC, sabieber approved these changes

2022-08-25 13:20 UTC, idlira approved these changes

2022-08-25 13:30 UTC, fhaScireum approved these changes

2022-08-26 08:46 UTC, qw3ry approved these changes

2022-08-26 12:18 UTC, merged