SIRI-615: Properly limits the height of Doughnut Charts.
scireum/sirius-biz pull request #1467
Opened 2022-09-02 09:30 UTC by fhaScireum

Previously, the set height of 180 was already ignored and instead, the chart was defined by the columns width.
This however now far exceeds the displayed height of the website.

Example:
![Bildschirmfoto 2022-09-02 um 11 28 10](https://user-images.githubusercontent.com/53555813/188109954-6238781c-1554-481c-bda5-46b08a441471.png)

2022-09-02 09:43 UTC, sabieber approved these changes

2022-09-02 13:04 UTC, andyHa commented
Fix uniformly for all charts?

2022-09-02 13:05 UTC, andyHa requested changes
Shouldn't we aply the same logic for all charts?

2022-09-05 08:01 UTC, sabieber approved these changes

2022-09-05 08:21 UTC, qw3ry approved these changes

2022-09-05 09:51 UTC, ymo-sci approved these changes

2022-09-05 11:06 UTC, merged