Adds a blob change handler that watches convertibility changes
scireum/sirius-biz pull request #1556
Opened 2022-12-16 14:40 UTC by cschierle

Needs changes from #1549

Fixes: [OX-9285](https://scireum.myjetbrains.com/youtrack/issue/OX-9285)

2022-12-19 08:27 UTC, andyHa requested changes

2022-12-19 08:27 UTC, andyHa commented on src/main/java/sirius/biz/storage/layer2/BlobConvertibilityChangedHandler.java
> +public interface BlobConvertibilityChangedHandler extends Priorized {
extract a super-interface for all BlobXXXChangedHandlers?

2022-12-19 08:27 UTC, andyHa commented on src/main/java/sirius/biz/storage/layer2/BlobConvertibilityChangedHandler.java
> + * Defines handlers to process {@link Blob blobs} after their {@link Blob#isInconvertible() convertibility status} changed.
add a remark that handlers must be registered....

2022-12-19 08:27 UTC, andyHa commented on src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
> +     */
```suggestion
     * Stores if the convertibility of the blob changed, e.g. after updating the physical file.
     * <p>
     * We store an extra flag here, which is internally toggled and then propagated via the
     * <tt>ProcessBlobChangesLoop</tt>
     * 
     */
```

2022-12-19 12:17 UTC, sabieber commented on src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
> +        if (isNew() || isChanged(CONVERTIBILITY_CHANGED)) {
Will this not result in the field being set back to true when it is set to false via `mango.update`?

2022-12-19 12:18 UTC, sabieber commented on src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
> +        if (isNew() || isChanged(CONVERTIBILITY_CHANGED)) {
s.a.

2023-01-13 07:37 UTC, cschierle commented
Replaced by https://github.com/scireum/sirius-biz/pull/1562

2023-01-13 07:37 UTC, closed without merging