Adds support for user-preferences and fixes some caching bugs in the TenantUserManager.
scireum/sirius-biz pull request #1726
Opened 2023-05-22 15:55 UTC by andyHa

Fixes: SIRI-810

2023-05-22 21:20 UTC, jakobvogel approved these changes

2023-05-23 05:39 UTC, mkeckmkeck commented on src/main/java/sirius/biz/tenants/BaseTenantAutoSetup.java
> +    @ConfigValue("security.system-saml.external-login-interval-days")
Doesn't match with example key from config: externalLoginIntervalDays

2023-05-23 05:39 UTC, mkeckmkeck commented on src/main/java/sirius/biz/tenants/UserAccountData.java
> +                parsedUserPreferences = Json.MAPPER.convertValue(Json.parseObject(userPreferences),
Use Json.convertToMap instead of using the mapper

2023-05-23 07:00 UTC, idlira requested changes

2023-05-23 07:00 UTC, idlira commented on src/main/java/sirius/biz/tenants/UserAccountData.java
> +    public Map<String, Object> getUserPreferences() {
rename to fetchUserPreferences / parseUserPreferences, since this is no direct getter?

2023-05-23 11:36 UTC, idlira approved these changes

2023-05-23 11:37 UTC, sabieber approved these changes

2023-05-23 11:39 UTC, jakobvogel approved these changes

2023-05-23 11:52 UTC, merged