Lokalise: Translations update
scireum/sirius-biz pull request #1748
Opened 2023-06-15 10:22 UTC by scireumskip

This pull request was initiated by Lokalise (user Matthias Brunner) at 2023-06-15 12:22:30

2023-06-15 11:04 UTC, idlira approved these changes

2023-06-19 18:23 UTC, sabieber requested changes

2023-06-19 18:23 UTC, sabieber commented on src/main/resources/biz_fr.properties
> +BaseFileParameter.invalidFileExtension = Le fichier '${nom}' n'a aucune des extensions de fichier valides : ${extensions}
**Required:** Variable got translated here

2023-06-20 08:03 UTC, ymo-sci commented on src/main/resources/biz_fr.properties
> +BaseFileParameter.invalidFileExtension = Le fichier '${nom}' n'a aucune des extensions de fichier valides : ${extensions}
```suggestion
BaseFileParameter.invalidFileExtension = Le fichier '${name}' n'a aucune des extensions de fichier valides : ${extensions}
```
also fixed in lokalise

2023-06-20 08:54 UTC, merged