Provides images in tenants an user accounts lists
scireum/sirius-biz pull request #1752
Opened 2023-06-20 12:15 UTC by cschierle

Tenants List:
![Bildschirmfoto 2023-06-20 um 14 07 38](https://github.com/scireum/sirius-biz/assets/42942954/c833e3e6-5bc0-43a8-ab1f-5c30f44067f4)

"Select Tenant" and "User Accounts List" use the same layout with images.

Also extracts user account details to a separate template for reusability, as was also done with tenant details in commit [1201d1914b429743fa053000466099af03a2238d](https://github.com/scireum/sirius-biz/pull/1723/commits/1201d1914b429743fa053000466099af03a2238d).

2023-06-20 12:20 UTC, idlira requested changes
we should replace previous calls of fetchSmallUrl to fetchMediumUrl and fetchMediumUrl to fetchLargeUrl

2023-06-20 12:27 UTC, cschierle commented
> we should replace previous calls of fetchSmallUrl to fetchMediumUrl and fetchMediumUrl to fetchLargeUrl

no previous usages of `fetchSmallUrl`

2023-06-20 12:28 UTC, sabieber approved these changes

2023-06-21 04:59 UTC, jmuscireum requested changes
Mark as breaking and please describe what has to be done to migrate

2023-06-21 04:59 UTC, jmuscireum commented on src/main/resources/default/templates/biz/tenants/tenant.html.pasta
> +                        <t:blobImage skipEmpty="true" urlBuilder="tenant.getTenantData().fetchLargeUrl()"
IMAGE_VARIANT_LARGE in line 44

2023-06-21 04:59 UTC, jmuscireum commented on src/main/resources/default/templates/biz/tenants/user-account.html.pasta
> +                        <t:blobImage skipEmpty="true" urlBuilder="account.getUserAccountData().fetchLargeUrl()"
IMAGE_VARIANT_LARGE in line 108

2023-06-21 04:59 UTC, jmuscireum commented on src/main/resources/default/templates/biz/tenants/user-account.html.pasta
> +                        <t:blobImage skipEmpty="true" urlBuilder="account.getUserAccountData().fetchLargeUrl()"
Also in profile.html.pasta

2023-06-21 06:37 UTC, idlira approved these changes

2023-06-21 06:42 UTC, sabieber approved these changes

2023-06-21 06:49 UTC, mkeckmkeck approved these changes

2023-06-21 06:57 UTC, jmuscireum approved these changes

2023-06-21 08:08 UTC, merged