Tycho Tenant/User UI Feedback
scireum/sirius-biz pull request #1755
Opened 2023-06-22 08:08 UTC by cschierle

Addresses several requests from initial feedback to the new tenant/user UI.
See individual commits for further details.

Fixes: [SIRI-606](https://scireum.myjetbrains.com/youtrack/issue/SIRI-606)

### Tenant Card Layout with placeholders
<img width="1677" alt="tenant cards" src="https://github.com/scireum/sirius-biz/assets/42942954/f4d839bc-e7ec-4f2f-8c88-8419a6bfaa1b">

Note: empty addresses are merely an edge-case in prod environments

### Packages and upgrades as select fields
![packages](https://github.com/scireum/sirius-biz/assets/42942954/ef8f917f-ad4e-42e5-91a5-8a2b3bef8531)

### Last login and api token in user details
![apiCode](https://github.com/scireum/sirius-biz/assets/42942954/bfd6da00-16d5-445c-bba1-b591b1ff2aeb)

2023-06-22 08:14 UTC, jakobvogel approved these changes

2023-06-22 08:33 UTC, idlira approved these changes

2023-06-22 08:34 UTC, sabieber approved these changes

2023-06-22 09:08 UTC, andyHa requested changes

2023-06-22 09:08 UTC, andyHa commented on src/main/resources/default/templates/biz/tenants/user-account.html.pasta
> +                </i:if>
we actually want to get rid of API tokens, so we shouldn't promote them...

2023-06-22 09:08 UTC, andyHa commented on src/main/resources/default/templates/biz/tenants/user-account.html.pasta
> +                </i:if>
do we really need both - last login and last seen? the former isn't relevant to most admins

2023-06-23 07:41 UTC, mkeckmkeck approved these changes

2023-06-23 08:05 UTC, sabieber approved these changes

2023-06-23 11:46 UTC, merged