Adds taglib for switching between different display modes of lists (SIRI-877)
scireum/sirius-biz pull request #1841
Opened 2023-09-20 06:49 UTC by bkositza

For lists there are several ways to display them. For this there is now the new taglib. It currently switches between the two display modes "list" and "cards".

2023-09-20 06:55 UTC, jakobvogel reviewed
Is this a plain copy of the respective OX files? (As discussed in the standup with @ymo-sci) Or have things been changed?

2023-09-20 06:57 UTC, sabieber approved these changes

2023-09-20 06:58 UTC, bkositza commented
> Is this a plain copy of the respective OX files? (As discussed in the standup with @ymo-sci) Or have things been changed?

Only small things have changed, for example that we don't use MongoUserAccount, but only the interface, and ContentListLayout is now a class and not an enum. But at its core it is a simple copy.

2023-09-20 07:04 UTC, andyHa requested changes

2023-09-20 07:04 UTC, andyHa commented on src/main/resources/default/taglib/t/listLayoutSwitch.html.pasta
> +    });
can't we put this into the js lib?

2023-09-20 07:04 UTC, andyHa commented on src/main/resources/default/taglib/t/listLayoutSwitch.html.pasta
> +        document.querySelectorAll("a.list-link-cards").forEach(_link => {
classes used by JS should have the -js suffix

2023-09-20 07:04 UTC, andyHa commented on src/main/java/sirius/biz/tycho/ContentListLayout.java
> +        UserAccount<?, ?> user = UserContext.getCurrentUser().as(UserAccount.class);
a user doesn't need to be a UserAccount - we should use tryAs here and fallback to using parameters only

2023-09-20 07:27 UTC, mko-sci approved these changes

2023-09-20 10:52 UTC, jakobvogel commented on src/main/java/sirius/biz/tycho/ContentListLayout.java
> +                user.get().updatePreference(userPreferencesKey, null);
```suggestion
                userAccount.updatePreference(userPreferencesKey, null);
```

2023-09-20 10:52 UTC, jakobvogel commented on src/main/java/sirius/biz/tycho/ContentListLayout.java
> +                user.get().updatePreference(userPreferencesKey, displayMode.name());
```suggestion
                userAccount.updatePreference(userPreferencesKey, displayMode.name());
```

2023-09-20 10:56 UTC, jakobvogel commented on src/main/java/sirius/biz/tycho/ContentListLayout.java
> +        return fallback;
Sowas in der Art?
```suggestion
        return user.flatMap(userAccount -> userAccount.readPreference(userPreferencesKey).getEnum(DisplayMode.class)).orElse(fallback);
```

2023-09-20 11:14 UTC, sabieber approved these changes

2023-09-20 11:28 UTC, jakobvogel approved these changes

2023-09-20 11:28 UTC, jakobvogel commented on src/main/resources/default/assets/scripts/list-layout-switch.js
> + */
Nachdem der Javascript ja in tycho-biz.js zusammengemergt wird, würde ich den Copyright Kommentar hier rauslassen. Oder zumindest von der Methode drunter durch eine Leerzeile absetzen, damit es nicht wie eine Dokumentation davon aussieht.

2023-09-20 11:34 UTC, fhaScireum commented on src/main/resources/default/assets/scripts/list-layout-switch.js
> + */
Remove copyright declaration as it will be rendered and this file is not used independently but as part of another js file.

2023-09-20 11:34 UTC, fhaScireum commented on src/main/resources/default/assets/scripts/list-layout-switch.js
> +});
Wrap in `(function () { ........ })();` to not have the `extendUrlWithDisplayMode` function accessible in the global scope. If that feature is wanted, we should define it as a function of the `sirius` object.

2023-09-20 11:40 UTC, jakobvogel approved these changes

2023-09-20 11:42 UTC, fhaScireum approved these changes

2023-09-20 11:52 UTC, mkeckmkeck approved these changes

2023-09-20 15:51 UTC, ymo-sci approved these changes

2023-09-21 06:28 UTC, andyHa approved these changes

2023-09-21 06:29 UTC, merged