KB - Adds a check which makes sure that the template is rendering before...
scireum/sirius-biz pull request #1891
Opened 2023-11-27 14:36 UTC by mko-sci

...processing it further to prevent an exception

### Additional Notes

- This PR fixes or works on following ticket(s): [OX-10557](https://scireum.myjetbrains.com/youtrack/issue/OX-10557)
- This PR is related to PR: 

### Checklist

- [x] Code change has been tested and works locally
- [x] Code was formatted via IntelliJ and follows SonarLint & [best practices](https://scireum.myjetbrains.com/youtrack/articles/MISC-A-16/CodeStyle-JavaDoc)

2023-11-27 14:40 UTC, sabieber commented on src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
> +    private boolean isRendering(Template template, GlobalRenderContext context) {
Would prefer a name like `tryRender`

2023-11-27 14:42 UTC, idlira requested changes

2023-11-27 14:42 UTC, idlira commented on src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
> +            if (!isRendering(template, context)) {
Don't you want to check for isArticle before?

2023-11-27 14:42 UTC, idlira commented on src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
> +    private boolean isRendering(Template template, GlobalRenderContext context) {
```suggestion
    private boolean tryToRender(Template template, GlobalRenderContext context) {
```

2023-11-27 14:51 UTC, idlira commented on src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
> +            if (!isRendering(template, context)) {
Ah, thx... I linked the closed PR in the description, because it does not mention exactly why it was closed.

2023-11-27 16:17 UTC, idlira approved these changes

2023-11-27 18:14 UTC, mko-sci commented on src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
> +                return;
ne, nur abbrechen wenn es false zurück gibt und dementsprechend nicht gerendert werden kann

2023-11-27 18:57 UTC, jakobvogel commented on src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
> +                return;
Ich sehe, dass der Code das macht. 😇 Ich möchte wissen, ob das reicht. Bekommen wir ein fehlerhaftes Template anderweitig mit? Haben wir eine Chance, das zu entdecken? Oder sind wir darauf angewiesen, dass irgendwer irgendwann merkt, dass ein Artikel fehlt?

2023-11-27 20:23 UTC, sabieber commented on src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
> +                return;
Guter Punkt finde ich. Vielleicht sollten wir KBA Komponenten doch in n anderes Verzeichnis legen oder anderweitig markieren, statt den Mechanismus zu verbiegen

2023-11-28 09:00 UTC, mko-sci commented
We decided that the approach might swallow kb articles which have a problem. Therefore we are going to introduce a new "rule". In the future we are going to ignore templates inside the "kb" directory if the templates parent-folder name is "part".

2023-11-28 09:00 UTC, closed without merging