ExtractArchiveJob: Fixes job not stopping when cancelled by user, also changes state to use "cancelled" instead of "terminated"
scireum/sirius-biz pull request #2008
Opened 2024-06-17 15:19 UTC by scireum-mbo

### Description
Before:
Still unpacking:
<img width="934" alt="image" src="https://github.com/scireum/sirius-biz/assets/150906388/a3a78eb1-fea3-4297-bff5-bb79eafda3cc">
After unpacking:
<img width="864" alt="image" src="https://github.com/scireum/sirius-biz/assets/150906388/08686496-707a-4c4a-b7de-e0a96ee39040">

After:
<img width="847" alt="image" src="https://github.com/scireum/sirius-biz/assets/150906388/83fae11f-2793-4ef7-a997-53e318bd476a">

### Additional Notes

- This PR fixes or works on following ticket(s): [SIRI-972](https://scireum.myjetbrains.com/youtrack/issue/SIRI-972)

### Checklist

- [x] Code change has been tested and works locally
- [x] Code was formatted via IntelliJ and follows SonarLint & [best practices](https://scireum.myjetbrains.com/youtrack/articles/MISC-A-16/CodeStyle-JavaDoc)
- [ ] Patch Tasks: Is local execution of Patch Tasks necessary? If so, please also mark the PR with the tag.

2024-06-17 15:29 UTC, idlira requested changes

2024-06-17 15:43 UTC, jakobvogel approved these changes
(subject to the suggestions by @idlira)

2024-06-17 15:44 UTC, mko-sci approved these changes

2024-06-18 07:03 UTC, sabieber approved these changes
**Optional:** Could we only set the state message "Das Archiv wurde vollständig entpackt" when the job wasn't cancelled, too? In my opinion showing this is a bit misleading, as not all contains were extracted in that case.

2024-06-18 08:31 UTC, sabieber approved these changes

2024-06-18 08:36 UTC, jakobvogel approved these changes

2024-06-18 08:46 UTC, sabieber approved these changes

2024-06-18 09:24 UTC, idlira approved these changes

2024-06-18 13:20 UTC, merged