Sets max cached days for virtual URLs based on config value
scireum/sirius-biz pull request #2030
Opened 2024-08-28 06:06 UTC by bkositza

### Description

On some systems, images are exchanged very frequently (with the same name). Here we need a shorter cache time so that the wrong image is not displayed and a new variant for preview etc. can be created.

### Additional Notes

- This PR fixes or works on following ticket(s): https://scireum.myjetbrains.com/youtrack/issue/SE-13898/Topf-Bildvarianten-404-durch-Varnish-Redirect
### Checklist

- [x] Code change has been tested and works locally
- [x] Code was formatted via IntelliJ and follows SonarLint & [best practices](https://scireum.myjetbrains.com/youtrack/articles/MISC-A-16/CodeStyle-JavaDoc)
- [ ] Patch Tasks: Is local execution of Patch Tasks necessary? If so, please also mark the PR with the tag.

2024-08-28 06:29 UTC, idlira commented on src/main/resources/component-070-biz.conf
> +        maxCachedDaysForVirtualURL = -1
**Suggestion**: it would give more flexibility if this setting could be defined per space.

2024-08-29 06:32 UTC, sabieber approved these changes

2024-08-29 06:32 UTC, sabieber commented on src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
> +    private static final String CONFIG_KEY_MAX_VALIDITY_DAYS_VIRTUAL_URL = "maxValidityDaysForVirtualURL";
```suggestion
    private static final String CONFIG_KEY_MAX_VALIDITY_DAYS_VIRTUAL_URL = "maxValidityDaysForVirtualUrl";
```

2024-08-29 06:32 UTC, sabieber commented on src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
> +    protected int maxValidityDaysForVirtualURL;
```suggestion
    protected int maxValidityDaysForVirtualUrl;
```

2024-08-29 06:32 UTC, sabieber commented on src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
> +        this.maxValidityDaysForVirtualURL = config.get(CONFIG_KEY_MAX_VALIDITY_DAYS_VIRTUAL_URL).asInt(-1);
```suggestion
        this.maxValidityDaysForVirtualUrl = config.get(CONFIG_KEY_MAX_VALIDITY_DAYS_VIRTUAL_URL).asInt(-1);
```

2024-08-29 06:32 UTC, sabieber commented on src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
> +        return maxValidityDaysForVirtualURL;
```suggestion
        return maxValidityDaysForVirtualUrl;
```

2024-08-29 06:32 UTC, sabieber commented on src/main/java/sirius/biz/storage/layer2/URLBuilder.java
> +        result.append(computeAccessTokenForVirtualURL(blobKey + "-" + variant));
```suggestion
        result.append(computeAccessTokenForVirtualUrl(blobKey + "-" + variant));
```

2024-08-29 06:32 UTC, sabieber commented on src/main/java/sirius/biz/storage/layer2/URLBuilder.java
> +    private String computeAccessTokenForVirtualURL(String authToken) {
```suggestion
    private String computeAccessTokenForVirtualUrl(String authToken) {
```

2024-08-29 06:32 UTC, sabieber commented on src/main/resources/component-070-biz.conf
> +                maxValidityDaysForVirtualURL = -1
```suggestion
                maxValidityDaysForVirtualUrl = -1
```

2024-08-29 07:28 UTC, idlira requested changes
Question: Your last change made it visible that a per-space parameter already exists: `urlValidityDays`, which is also used for virtual URLs. So, is there a real use case to have 2 parameters? In fact physical URLs should be marked as often as it can be, eternallyValid, ensuring a better use of caching.

2024-08-29 08:28 UTC, closed without merging