Fixes backend search for Mongo codelists + codelist entries
scireum/sirius-biz pull request #867
Opened 2020-09-28 16:35 UTC by idlira

Error error: `Ein unerwarteter Fehler ist aufgetreten: MongoQueryCompiler only supports either a search in the FULLTEXT_FIELD or an equals or prefix search in a string field (java.lang.IllegalArgumentException)`

Note: Re-Save entities is needed for MongoCodeList and MongoCodeListEntry in order to update the search prefixes.

2020-09-28 17:40 UTC, andyHa commented on src/main/java/sirius/biz/codelists/CodeListController.java
> +    protected abstract void setCodeListSearchFields(BasePageHelper<L, ?, ?, ?> pageHelper);
applyXXX or the like?

2020-09-28 17:40 UTC, andyHa requested changes
...

2020-09-28 18:21 UTC, bwiedmann approved these changes

2020-09-28 19:08 UTC, andyHa approved these changes

2020-09-29 06:30 UTC, sabieber approved these changes

2020-09-29 06:30 UTC, sabieber commented on src/main/java/sirius/biz/codelists/jdbc/SQLCodeListController.java
> +        pageHelper.withSearchFields(QueryField.contains(CodeList.CODE_LIST_DATA.inner(CodeListData.CODE)),
Für SQL kann man nicht auch das SEARCH_PREFIXES Feld nehmen?

2020-09-29 06:35 UTC, mkeckmkeck approved these changes

2020-09-29 06:35 UTC, idlira commented on src/main/java/sirius/biz/codelists/jdbc/SQLCodeListController.java
> +        pageHelper.withSearchFields(QueryField.contains(CodeList.CODE_LIST_DATA.inner(CodeListData.CODE)),
Mongo exclusive as far as I know 😬

2020-09-29 07:50 UTC, merged