BREAKING CHANGE: Makes Job Parameters immutable.
scireum/sirius-biz pull request #904
Opened 2020-11-11 19:39 UTC by andyHa

As we more and more tend to use parameters as globally shared constants, it is neccesarry to make them immutable once shared.

Therefore we differentiate between "ParameterBuilder", which is the mutable way of setting up a parameter as wanted and "Parameter" itself, which is then an immutable object which can safely be shared.

This leads to some refactorings and simplifications, hence the amount of changed files. The actual changes are quite small.

2020-11-11 20:08 UTC, jakobvogel requested changes

2020-11-11 20:08 UTC, jakobvogel commented on src/main/java/sirius/biz/jobs/params/Parameter.java
>   * Defines a parameter which can be rendered in the UI and verify and extract a value from a context.
Who can verify and extract? The parameter? (Clarify?)

2020-11-11 20:08 UTC, jakobvogel commented on src/main/java/sirius/biz/jobs/params/ParameterBuilder.java
> + * A parameter is setup using sublasses of this class which are eventually converted using {@link #build()}.
```suggestion
 * A parameter is set up using subclasses of this class which are eventually converted using {@link #build()}.
```

2020-11-11 20:08 UTC, jakobvogel commented on src/main/java/sirius/biz/jobs/params/ParameterBuilder.java
> +     * Once the parameter is build, the builder itself should no longer be used.
```suggestion
     * Once the parameter is built, the builder itself should no longer be used.
```

2020-11-11 20:08 UTC, jakobvogel commented on src/main/java/sirius/biz/jobs/params/ParameterBuilder.java
> +     * @return the value represented as string
Which of the two `@return`?

2020-11-11 20:11 UTC, andyHa commented on src/main/java/sirius/biz/jobs/batch/file/ArchiveImportJob.java
> +        return "zip".equalsIgnoreCase(fileExtension);
This is due to another refactoring concerning archive files - consider this state temporary and the next PR will hopefully fix this...

2020-11-11 20:11 UTC, andyHa commented on src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
> +        } else if ("zip".equalsIgnoreCase(file.fileExtension())) {
s.a.

2020-11-11 20:28 UTC, jakobvogel approved these changes

2020-11-12 07:27 UTC, mkeckmkeck approved these changes

2020-11-12 07:36 UTC, sabieber approved these changes

2020-11-12 08:16 UTC, fhaScireum approved these changes

2020-11-12 08:18 UTC, idlira approved these changes

2020-11-12 08:20 UTC, sabieber approved these changes

2020-11-12 08:21 UTC, merged