Provides a minimal Redis management / query UI
scireum/sirius-biz pull request #920
Opened 2020-11-23 15:05 UTC by andyHa

2020-11-23 15:15 UTC, sabieber requested changes

2020-11-23 15:15 UTC, sabieber commented on src/main/java/sirius/biz/util/RedisController.java
> +    public void executeQuery(WebContext ctx, JSONStructuredOutput out) {
ctx -> webContext

2020-11-23 15:15 UTC, sabieber commented on src/main/java/sirius/biz/util/RedisController.java
> +        out.property("result", sb.toString());
```suggestion
        StringBuilder resultBuilder = new StringBuilder();
        renderResult(result, "", resultBuilder);
        out.property("result", resultBuilder.toString());
```

2020-11-23 15:15 UTC, sabieber commented on src/main/java/sirius/biz/util/RedisController.java
> +    }
```suggestion
    private void renderResult(Object result, String offset, StringBuilder resultBuilder) {
        if (result instanceof List) {
            List<?> results = (List<?>) result;
            for (int i = 0; i < results.size(); i++) {
                if (i > 0) {
                    resultBuilder.append(offset);
                }
                resultBuilder.append(Strings.apply("%2d", i + 1));
                resultBuilder.append(") ");
                renderResult(results.get(i), offset + "    ", resultBuilder);
            }
        } else if (result instanceof byte[]) {
            resultBuilder.append(SafeEncoder.encode((byte[]) result));
            resultBuilder.append("\n");
        } else {
            resultBuilder.append(NLS.toUserString(result));
            resultBuilder.append("\n");
        }
    }
```

2020-11-23 15:19 UTC, idlira approved these changes

2020-11-25 06:26 UTC, mkeckmkeck approved these changes

2020-11-26 09:18 UTC, merged