Provides a simple scripting facility for system administrators.
scireum/sirius-biz pull request #972
Opened 2021-01-29 12:42 UTC by andyHa

Permits to run Noodle scripts on a random, a dedicated or even all hosts at once:

![grafik](https://user-images.githubusercontent.com/875799/106276397-d028f300-6237-11eb-8b2e-c4010a4f1ae2.png)

2021-01-29 12:51 UTC, idlira requested changes
mini typo

2021-01-29 12:51 UTC, idlira commented on src/main/java/sirius/biz/ide/Scripting.java
> + * Note however, that this commonication is performed via our central interconnect and thus shouldn't
```suggestion
 * Note however, that this communication is performed via our central interconnect and thus shouldn't
```

2021-01-29 16:12 UTC, idlira approved these changes

2021-02-01 15:55 UTC, sabieber requested changes

2021-02-01 15:55 UTC, sabieber commented on src/main/java/sirius/biz/ide/JobTaskContextAdapter.java
> +    public void setState(String message) {
comment empty method?

2021-02-01 15:55 UTC, sabieber commented on src/main/java/sirius/biz/ide/JobTaskContextAdapter.java
> +    public void addTiming(String counter, long millis) {
s.o.

2021-02-01 15:55 UTC, sabieber commented on src/main/java/sirius/biz/ide/Scripting.java
> + * be used to heavy (like outputting 1000s of lines per second).
```suggestion
 * be used too heavy (like outputting 1000s of lines per second).
```

2021-02-01 15:55 UTC, sabieber commented on src/main/java/sirius/biz/ide/Scripting.java
> +        // For audit and tracing purposes we also log this to into the system logs...
```suggestion
        // For audit and tracing purposes we also log this into the system logs...
```

2021-02-01 15:55 UTC, sabieber commented on src/main/java/sirius/biz/ide/Scripting.java
> +        logInTranscript(jobNumber, Strings.apply("Executing %s on %s", jobNumber, CallContext.getNodeName()));
Does this duplicate the jobnumber (as in is the jobNumber param printed anywhere in the ui?)? sometimes it is only transferred as a message parameter, other times it is also written in the logged message.

2021-02-01 15:55 UTC, sabieber commented on src/main/java/sirius/biz/ide/Scripting.java
> +        logInTranscript(jobNumber, Strings.apply("Execution completed (%s)", watch.duration()));
In relation to my other comment: This just passes the jobNumber as parameter but doesnt print the jobNumber of the completed job in the message

2021-02-01 15:55 UTC, sabieber commented on src/main/java/sirius/biz/ide/ScriptingController.java
> +        nodes.add(Tuple.create("All Machines", "*"));
This could reuse the Scripting.ALL_NODES constant

2021-02-01 15:55 UTC, sabieber commented on src/main/java/sirius/biz/ide/ScriptingController.java
> +            String targetNode = webContext.get(PARAM_NODE).ignore("-").asString();
extract "-" as CURRENT_NODE? Two semantically similar usages.

2021-02-02 12:02 UTC, qw3ry approved these changes

2021-02-04 08:05 UTC, bwiedmann commented on src/main/java/sirius/biz/ide/Scripting.java
> + * Note however, that this commonication is performed via our central interconnect and thus shouldn't
Noch offen

2021-02-04 08:09 UTC, bwiedmann requested changes
Mini typo

2021-02-04 08:09 UTC, bwiedmann commented on src/main/java/sirius/biz/ide/Scripting.java
> +     * current machine or it can be set to "*" to run on all machines simulatenously.
```suggestion
     * current machine or it can be set to "*" to run on all machines simultaneously.
```

2021-02-04 10:01 UTC, sabieber requested changes

2021-02-04 10:01 UTC, sabieber commented on src/main/java/sirius/biz/ide/Scripting.java
> +<<<<<<< HEAD
Da ist ein Merge reingerutscht

2021-02-04 10:01 UTC, sabieber approved these changes

2021-02-10 08:05 UTC, bwiedmann approved these changes

2021-02-15 09:26 UTC, merged