Provides a job which permits to force a full synchronization of a giv…
scireum/sirius-biz pull request #998
Opened 2021-02-17 11:09 UTC by andyHa

…en object storage space.

2021-02-17 11:11 UTC, sabieber requested changes

2021-02-17 11:11 UTC, sabieber commented on src/main/java/sirius/biz/storage/layer1/replication/ForceReplicationJob.java
> + * This is most commonly used after as new replication target has been defined in order to copy the existing
```suggestion
 * This is most commonly used after a new replication target has been defined in order to copy the existing
```

2021-02-17 11:11 UTC, sabieber commented on src/main/resources/biz_de.properties
> +ForceReplicationJob.jobTitle = Erwzinge vollständige Replikation von '${space}
```suggestion
ForceReplicationJob.jobTitle = Erwzinge vollständige Replikation von '${space}'
```

2021-02-17 11:12 UTC, idlira approved these changes

2021-02-17 11:13 UTC, meg1502 approved these changes

2021-02-17 15:57 UTC, cschierle approved these changes

2021-02-17 15:57 UTC, cschierle commented on src/main/resources/biz_de.properties
> +ForceReplicationJob.jobTitle = Erwzinge vollständige Replikation von '${space}'
```suggestion
ForceReplicationJob.jobTitle = Erzwinge vollständige Replikation von '${space}'
```
Typo

2021-02-18 06:26 UTC, jmuscireum approved these changes

2021-02-18 06:27 UTC, merged